Text_ObtainedTheX::
	.string "Obtained the {STR_VAR_2}!$"

Text_BagIsFull::
	.string "The BAG is full…$"

Text_PutItemAway::
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

Text_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

Text_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

Text_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"

Text_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

Text_RelearnerKit_Confirm::
	.string "Do you want to relearn\n"
	.string "a move?$"

Text_RelearnerKit_CannotTutorEgg::
    .string "You cannot tutor an egg.$"

Text_RelearnerKit_NoMove::
    .string "No move to tutor.$"
