FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "I'm the FISHING GURU's older\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and scale\n"
    .string "WATERFALLs, young friend!$"

FuchsiaCity_House2_Text_ReceivedHM07::
    .string "{PLAYER} received HM07 from\n"
    .string "the FISHING GURU's brother.$"

FuchsiaCity_House2_Text_CanCatchBetterMons::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "With the ability to scale,\n"
    .string "WATERFALLS, you can\p"
    .string "catch much better POKéMON.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it!$"

