Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "VERMILION CAVE$"

Route2_Text_RickIntro::
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

Route2_Text_RickDefeat::
    .string "No!\nCATERPIE can't hack it!$"

Route2_Text_RickPostBattle::
    .string "The trainers in Viridian\n"
    .string "Forest are too strong for me.$"
